##################################################
##  configuration file.                     ##
## Use this file to customize your  analysis ##
##################################################

SE_SUFFIX: ".fastq"
R1_SUFFIX: "_R1.fastq"
#R2_SUFFIX: "_R2.fastq.bz2"
STAR_INDEX_PATH: "/mnt/tscc/share/STAR_indices/"
